lang: "de"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Covid 19 im Kreis Höxter" # the name of your site, e.g. ACME Corp.

defaults:
  - scope:
      path: ""
      type: "communes"
    values:
      layout: "commune"
  - scope:
      path: "index"
    values:
      layout: "home"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  communes:
    output: true

